Create MenuItemReview Database
ucsb-cs156-f22/team02-f22-7pm-3 pull request #36
Opened 2022-10-26 00:42 UTC by wesleykam

In this PR, I created the MenuItemReview Database with the @Entity and @Repository classes.

closes #15

2022-10-26 01:10 UTC, ethwu requested changes
Need to update entity name but otherwise lgtm!

2022-10-26 01:10 UTC, ethwu commented on src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
> +@Entity(name = "menuitemreview")
I think this should be `"menuitemreviews"`.

2022-10-28 00:19 UTC, wesleykam commented
Fixed issue waiting for reapproval

2022-10-28 00:24 UTC, ethwu approved these changes
LGTM1

2022-10-28 01:00 UTC, merged